#!/usr/bin/env bash
# Copy fresh dist artifacts (simd-tooltips.js + simd-names.json + simd-data.json)
# into ./dist/ so the static site can serve them. Run after the database is
# regenerated by ../scripts/build_all.sh.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/../simd-tooltip/dist"
DEST="$HERE/dist"

if [[ ! -d "$SRC" ]]; then
    echo "error: $SRC not found. Run scripts/build_all.sh first." >&2
    exit 1
fi

mkdir -p "$DEST"
for f in simd-tooltips.js simd-names.json simd-data.json; do
    cp "$SRC/$f" "$DEST/$f"
    printf '  %12d B  %s\n' "$(wc -c < "$DEST/$f" | tr -d ' ')" "$DEST/$f"
done
